### ISSUE TITLE
Editing project/tag/workspace in any workspaces switches to default workspace.

### ISSUE THREAD

**Issue by AnujaK** [AnujaK/restfiddle#203]
Edit project in any workspace other than default (demo workspace). When save changes is clicked, the workspace changes to default one. Similarly for edit tag/workspace.

**Comment by abdotalaat** [comment]
the problem especially occurs when any reload for page if the user changed the workspace and reload the page the workspace changes to default .

**Comment by AnujaK** [comment]
@kshijiD After merging pull request #229 , following bugs persist: * DeleteProject/ DeleteTag switches to default workspace. * Adding new tag is not immediately visible (till user clicks Refresh icon of browser).
