### ISSUE TITLE
question : i created tag , how assign my request to this tag

### ISSUE THREAD

**Issue by abdotalaat** [AnujaK/restfiddle#206]

**Comment by AnujaK** [comment]
Has been assigned to @kshijiD

**Comment by AnujaK** [comment]
We can now assign tags to a request and rescpective tags visible when request is navigated through project.
Not closing the issue as the tags are not displayed when the request is navigated from 'Tags' rather than from project.

**Comment by AnujaK** [comment]
Fixed in pull reques #225 .
