### ISSUE TITLE
Filtering/searching should work by passing query params

### ISSUE THREAD

**Issue by AnujaK** [AnujaK/restfiddle#234]
find, in, regex etc. should work on GET queries.

**Comment by mihasandor** [comment]
Is anyone working on this?

**Comment by AnujaK** [comment]
@mihasandor  Not yet.

**Comment by AnujaK** [comment]
@rka12 For regex, you can refer http://docs.mongodb.org/manual/reference/operator/query/regex/

**Comment by rka12** [comment]
Working on it.

**Comment by rka12** [comment]
PR created #421 

Examples query params

1. Sort
 sort ={username:-1} 
sort by username field in descending order

2. Simple search
 query={username:"user1"}
search records for username equals to user1

3. Search with regex
 query={username:{ $regex: "^u.*" }} 
search record  for username starts with u

Other mongodb operator will also work

**Comment by AnujaK** [comment]
@rka12 Please paste a few complete urls to serve as examples.
