### ISSUE TITLE
Auto-suggest shows only localhost urls.Should suggest all requests run so far.

### ISSUE THREAD

**Issue by AnujaK** [AnujaK/restfiddle#247]
It should show in runtime.

**Comment by aashish13** [comment]
Anyone working on this issue?
I plan to work on this.

**Comment by AnujaK** [comment]
@aashish13 No one working on it yet. You may take it up. Autosuggest doesn't show urls in runtime. If  you login next time, you get all the relevant urls in autosuggest.

**Comment by AnujaK** [comment]
It got fixed in the latest commits.
