### ISSUE TITLE
API Name in second column should get trimmed based on column width and not be limited to 140 characters.

### ISSUE THREAD

**Issue by AnujaK** [AnujaK/restfiddle#328]

**Comment by for-singer** [comment]
Is it possible to implement it using CSS only? I see the possibility to do it by JS.

**Comment by AnujaK** [comment]
@for-singer Any solution would do- js or css. Ideally the length of text shown should be dependent on browser size. So even if at runtime the browser size changes, it should adapt to the new size.
Let me know if you would like to take it up. I'll assign it to you.

**Comment by for-singer** [comment]
Yes, please.

**Comment by AnujaK** [comment]
Assigned to @for-singer . Take the update before you start working.

**Comment by for-singer** [comment]
@AnujaK I made solution using js in the browser's console. So now I need to get the right place to paste it to be handled by such events like render, element change size and "#tree" vertical scroll appears or disappears. I think that maybe it can be done in the 'tree-view.js' file. Could you explain me in details where can i paste it?

**Comment by AnujaK** [comment]
@for-singer  Logically speaking, yes it should be part of tree-view. Try adding it and test it thoroughly before you send a pull request.

**Comment by AnujaK** [comment]
Fixed with PR #346
