### ISSUE TITLE
Entity Authorization using auth-token

### ISSUE THREAD

**Issue by AnujaK** [AnujaK/restfiddle#355]

**Comment by AnujaK** [comment]
Auth token returned in Login User request.
"authToken": "55ffa6fcd40f73fb96c37a2b", "user": { "password": "$2a$10$qvauDtVIE0BqvstYHi.b8ufVkeGgxOwWPOr1KGaOJmuWzUvMvsxvi", "_id": "55ffa6d1d40f73fb96c37a1d", "username": "aaa" }

However, in no case should password be returned in any response. @rka12 to rectify the response returned.

**Comment by rka12** [comment]
work in progress

**Comment by AnujaK** [comment]
@rka12  authToken is not returned in response. How will Logout User work?

**Comment by rka12** [comment]
Simple authorization completed (PR #360) 

Role based authorization work in progress
