### ISSUE TITLE
[4h] Display a warning message whenever an in-memory database is used.

### ISSUE THREAD

**Issue by ranjan-rk** [AnujaK/restfiddle#88]
Here is the message - 

The current installation uses in-memory database. In-memory database should be used for testing purpose only. Update config to use MySQL or any other compatible database.

**Comment by AnujaK** [comment]
UI design needs to finalized- when (on login or when used), how (pop-up or like a notification) and what(text) to show in the message.

**Comment by AnujaK** [comment]
Since we are using mongodb now...it is not required.
